services:
  postgres:
    platform: linux/amd64
    container_name: postgres
    image: postgres:16.1-alpine
    networks:
      - main
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    platform: linux/amd64
    container_name: mongodb
    image: mongo:7.0.5
    networks:
      - main
    ports:
      - "27017:27017"
    env_file:
      - .env.dev
    volumes:
      - mongodb_data:/data/db

  backend:
    platform: linux/amd64
    container_name: backend
    networks:
      - main
    ports:
      - "12345:12345"
    depends_on:
      - postgres
      - mongodb
    build: ./backend
networks:
  main:

volumes:
  postgres_data:
  mongodb_data:
