services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    networks:
      - main
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27017:27017"
    env_file:
      - .env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  adminer:
    image: adminer
    networks:
      - main
    restart: always
    ports:
      - 8080:8080

networks:
  main:

volumes:
  postgres_data:
  mongodb_data:
